More openstack-deploy scripting

diff --git a/src/openstack-deploy b/src/openstack-deploy
--- a/src/openstack-deploy
+++ b/src/openstack-deploy
@@ -4,8 +4,13 @@ set -e
 
 ACTION=${1}
 
+if ! [ -r /usr/share/openstack-deploy/preseed-lib ] ; then
+	echo "Can't find /usr/share/openstack-deploy/pressed-lib: exiting"
+	exit 1
+fi
+. /usr/share/openstack-deploy/preseed-lib
+
 OSINSTALL_RC=osinstallrc
-APTGET="apt-get -o Dpkg::Options::=--force-confnew --force-yes -fuy"
 
 osinstall_gen_pass () {
 	GENERATED_PASSWORD=$(dd if=/dev/random bs=64 count=1 2>|/dev/null | md5sum | awk '{print $1}')
@@ -22,6 +27,14 @@ osinstall_check_installed () {
 	fi
 }
 
+osinstall_install_if_not_installed () {
+	local PKG_NAME
+	PKG_NAME=${1}
+	if ! osinstall_check_installed ${PKG_NAME} ; then
+		${APTGET} install ${PKG_NAME}
+	fi
+}
+
 osinstall_rcvalue () {
 	local RC_VARNAME RC_VARCONTENT RC_MESSAGE RC_ISPASS RC_DEFAULT
 	RC_VARNAME=${1}
@@ -29,6 +42,7 @@ osinstall_rcvalue () {
 	RC_ISPASS=${3}
 	RC_DEFAULT=${4}
 	RC_VARCONTENT=${!RC_VARNAME}	# TODO: find a way to work out this in ISO sh
+	# using something like: eval "RC_VARCONTENT=\$$RC_VARNAME"
 	if [ -z "${RC_VARCONTENT}" ] ; then
 		echo -n "${RC_MESSAGE}"
 		read RC_VARCONTENT
@@ -68,17 +82,82 @@ ${RC_MYSQL_SERVER_PKG_NAME} mysql-server/root_password seen true
 ${RC_MYSQL_SERVER_PKG_NAME} mysql-server/root_password_again password ${RC_MYSQL_PASSWORD}
 ${RC_MYSQL_SERVER_PKG_NAME} mysql-server/root_password_again seen true
 " | debconf-set-selections
-		${APTGET} ${RC_MYSQL_SERVER_PKG_NAME}
+		${APTGET} install ${RC_MYSQL_SERVER_PKG_NAME}
 	fi
+}
+
+osinstall_install_services () {
+	os_pressed_misc
+	osinstall_mysql_server
+	osinstall_install_if_not_installed mongodb
+	osinstall_install_if_not_installed rabbitmq-server
+	osinstall_install_if_not_installed ntp
+	osinstall_install_if_not_installed python-argparse
+	osinstall_install_if_not_installed openstack-cloud-services
+}
+
+osinstall_rabbit_host_and_pass () {
+	osinstall_rcvalue RC_RABIT_HOST "Rabbit-MQ host [127.0.0.1]: " no 127.0.0.1
+	osinstall_rcvalue RC_RABIT_USER "Rabbit-MQ user [guest]: " no guest
+	osinstall_rcvalue RC_RABIT_PASS "Rabbit-MQ password [generated-password]: " yes
+	if [ "${RC_RABIT_HOST}" = 127.0.0.1 ] && [ -x /usr/sbin/rabbitmqctl ] ; then
+		rabbitmqctl change_password guest ${RC_RABIT_PASS}
+	fi
+}
+
+osinstall_rcvalue_keystone_endpoint () {
+	DEFROUTE_IF=`LC_ALL=C /sbin/route | grep default |awk -- '{ print $8 }' | cut -d" " -f1`
+	if [ -n "${DEFROUTE_IF}" ] ; then
+		DEFROUTE_IP=`LC_ALL=C ip addr show "${DEFROUTE_IF}" | grep inet | head -n 1 | awk '{print $2}' | cut -d/ -f1 | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'`
+	fi
+	osinstall_rcvalue RC_KEYSTONE_ENDPOINT_IP "Keystone endpoint IP address [${DEFROUTE_IP}]: " no ${DEFROUTE_IP}
+	osinstall_rcvalue RC_KEYSTONE_REGION "Keystone endpoint region [regionOne]: " no regionOne
+}
+
+osinstall_keystone () {
+	if [ -z "${RC_KEYSTONE_ENDPOINT_IP}" ] ; then
+		osinstall_rcvalue_keystone_endpoint
+	fi
+	osinstall_rcvalue RC_KEYSTONE_AUTHTOKEN "Keystone authtoken [generated-password]: " yes
+	osinstall_rcvalue RC_KEYSTONE_ADMINPASS "Keystone admin tenant password [generated-password]: " yes
+	osinstall_rcvalue RC_KEYSTONE_SQL_PASS "Keystone MySQL password [generated-password]: " yes
+	os_install_keystone ${RC_KEYSTONE_AUTHTOKEN} ${RC_KEYSTONE_ADMINPASS} ${RC_KEYSTONE_ENDPOINT_IP} ${RC_KEYSTONE_REGION} ${RC_KEYSTONE_SQL_PASS} ${RC_MYSQL_PASSWORD}
+}
+
+osinstall_glance () {
+	osinstall_rcvalue RC_GLANCE_SQL_PASS "Glance MySQL password [generated-password]: " yes
+	os_preseed_glance ${RC_GLANCE_SQL_PASS} ${RC_MYSQL_PASSWORD} \
+		${RC_KEYSTONE_ENDPOINT_IP} ${RC_KEYSTONE_REGION} ${RC_KEYSTONE_ADMINPASS} \
+		${RC_RABIT_HOST} ${RC_RABIT_USER} ${RC_RABIT_PASS}
+}
+
+osinstall_glance () {
+	osinstall_rcvalue RC_NOVA_SQL_PASS "Nova MySQL password [generated-password]: " yes
+	os_preseed_nova ${RC_NOVA_SQL_PASS} ${RC_MYSQL_PASSWORD} \
+		${RC_KEYSTONE_ENDPOINT_IP} ${RC_KEYSTONE_REGION} ${RC_KEYSTONE_ADMINPASS} \
+		${RC_RABIT_HOST} ${RC_RABIT_USER} ${RC_RABIT_PASS}
 }
 
 case "${1}" in
 "controller")
+	os_pressed_misc
+	osinstall_install_services
+	osinstall_rabbit_host_and_pass
+	osinstall_keystone
 ;;
 "compute")
+	os_pressed_misc
+	osinstall_install_if_not_installed ntp
+	osinstall_install_if_not_installed python-argparse
+	osinstall_rcvalue_keystone_endpoint
 ;;
 "all-in-one")
-	osinstall_mysql_server
+	os_pressed_misc
+	osinstall_install_if_not_installed ntp
+	osinstall_install_if_not_installed python-argparse
+	osinstall_install_services
+	osinstall_rabbit_host_and_pass
+	osinstall_keystone
 ;;
 *)
 	usage
